title:       Mig Reyes
subtitle:    "Design Lead, Trunk Club"
description: Mig is a Design Lead at Trunk Club helping redesign retail.

author:    Mig Reyes
github:    http://github.com/migreyes
twitter:   http://twitter.com/migreyes
dribbble:  http://dribbble.com/migreyes
instagram: http://instagram.com/migreyes
pinterest: http://pinterest.com/migreyes

source:      _source
destination: public
exclude:     [public, Gemfile, Gemfile.lock, Rakefile, README.md]

markdown:  rdiscount
permalink: /:categories/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      title: "Mig Reyes, Design Lead at Trunk Club"
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      category: shares

sass:
  style:    :compressed
  sass_dir: assets/stylesheets